language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - '7.3'
    - nightly
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm
        - php: hhvm-nightly
    fast_finish: true

before_script:
    - export DISPLAY=:99.0
    - Xvfb $DISPLAY -extension RANDR &> /dev/null &

    - curl http://selenium-release.storage.googleapis.com/3.9/selenium-server-standalone-3.9.1.jar > selenium.jar
    - java -jar selenium.jar &> /dev/null &
    - sleep 5

    - php -S localhost:8080 -t tests/fixtures/www &> /dev/null &
    - cp behat.yml{.dist,}
    - composer install

script:
    - ./bin/atoum
    - ./bin/behat -fprogress --tags='~@user'

    - ./bin/box build
    - sed -i 's/Sanpi\\Behatch\\Extension/behatch_contexts.phar/' behat.yml
    - ./bin/behat -fprogress --tags='~@user'
